import CountryData from "@/components/DataCountry";
import Link from "next/link";

const CountryPage = ({ params }: { params: { country: string } }) => {
  const { country } = params;
  const countData = CountryData.find(
    (c) => c.code.toLowerCase() === country.toLowerCase()
  );

  if (!countData) {
    return (
      <div className="max-w-96 m-auto my-20 px-8 py-4 rounded-2xl bg-red-700 text-center">
        <h1 className="py-2 text-white font-bold text-2xl">
          Country not found
        </h1>
        <hr />
        <p className="text-white pt-4 text-lg">
          Not a member of <span className="font-bold">United Nations</span>
        </p>
        <p className="text-white text-lg">or entered wrong spelling</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col mt-6 m-auto max-w-[700px] px-4">
      <div className="flex flex-wrap gap-4 items-center">
        <img
          className="w-36 h-24 border-2 border-solid rounded-lg"
          src={countData.url}
          alt={`${countData.name} Flag`}
        />
        <h1 className="font-bold text-6xl text-slate-900">{countData.name}</h1>
      </div>
      <div className="result mt-2">
        <p>
          Full Name: <span>{countData.fullName}</span>
        </p>
        <p>
          Name in Native Language: <span>{countData.nameInNativeLang}</span>
        </p>

        <p>
          Capital City: <span>{countData.capitalCity}</span>
        </p>
        <p>
          Largest City: <span>{countData.largestCity}</span>
        </p>
        <p>
          Official Languages: <span>{countData.officialLanguages}</span>
        </p>
        <p>
          Religion: <span>{countData.religion}</span>
        </p>
        <p>
          Population: <span>{countData.population}</span>
        </p>
        <p>
          Rank by Population: <span>{countData.rankByPopulation}</span>
        </p>
        <p>
          Independence: <span>{countData.independence}</span>
        </p>
        <p>
          Area:{" "}
          <span>
            {countData.area} km<sup>2</sup>
          </span>
        </p>
        <p>
          Currency: <span>{countData.currency}</span>
        </p>
        <Link href="/countries">
          <button className="px-8 py-2 bg-green-800 my-4 font-bold text-white hover:bg-green-700 ease-in duration-300">
            Back
          </button>
        </Link>
        <h6 className="bg-red-600 font-normal text-white text-sm px-4 py-1 text-center">
          Please note: Country information is generated by ChatGPT, may includes
          sensitive mistakes
        </h6>
      </div>
    </div>
  );
};

export default CountryPage;
