interface Data {
  code: string;
  url: string;
  name: string;
  fullName: string;
  nameInNativeLang: string;
  capitalCity: string;
  largestCity: string;
  officialLanguages: string;
  religion: string;
  population: string;
  rankByPopulation: string;
  independence: string;
  area: string;
  currency: string;
}
const CountryData: Data[] = [
  {
    code: "Afghanistan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/1280px-Flag_of_the_Taliban.svg.png",
    name: "Afghanistan",
    fullName: "Islamic Republic of Afghanistan",
    nameInNativeLang: "د افغانستان اسلامي امارت",
    capitalCity: "Kabul",
    largestCity: "Kabul",
    officialLanguages: "Pashto, Dari",
    religion: "Islam",
    population: "39,835,428",
    rankByPopulation: "39",
    independence: "19-Aug-1919",
    area: "652,230",
    currency: "Afghan Afghani (AFN)",
  },
  {
    code: "Albania",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/800px-Flag_of_Albania.svg.png",
    name: "Albania",
    fullName: "Republic of Albania",
    nameInNativeLang: "Republika e Shqipërisë",
    capitalCity: "Tirana",
    largestCity: "Tirana",
    officialLanguages: "Albanian",
    religion: "Islam, Christianity",
    population: "2,845,955",
    rankByPopulation: "140",
    independence: "28-Nov-1912",
    area: "28,748",
    currency: "Albanian Lek (ALL)",
  },
  {
    code: "Algeria",
    url: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg",
    name: "Algeria",
    fullName: "People's Democratic Republic of Algeria",
    nameInNativeLang: "الجمهورية الجزائرية الديمقراطية الشعبية",
    capitalCity: "Algiers",
    largestCity: "Algiers",
    officialLanguages: "Arabic, Berber",
    religion: "Islam",
    population: "45,351,000",
    rankByPopulation: "32",
    independence: "05-Jul-1962",
    area: "2,381,741",
    currency: "Algerian Dinar (DZD)",
  },
  {
    code: "Andorra",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/800px-Flag_of_Andorra.svg.png",
    name: "Andorra",
    fullName: "Principality of Andorra",
    nameInNativeLang: "Principat d'Andorra",
    capitalCity: "Andorra la Vella",
    largestCity: "Andorra la Vella",
    officialLanguages: "Catalan",
    religion: "Catholicism",
    population: "77,142",
    rankByPopulation: "179",
    independence: "Andorran co-princes",
    area: "468",
    currency: "Euro (EUR)",
  },
  {
    code: "Argentina",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/800px-Flag_of_Argentina.svg.png",
    name: "Argentina",
    fullName: "Argentine Republic",
    nameInNativeLang: "República Argentina",
    capitalCity: "Buenos Aires",
    largestCity: "Buenos Aires",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "45,376,763",
    rankByPopulation: "32",
    independence: "09-Jul-1816",
    area: "2,780,400",
    currency: "Argentine Peso (ARS)",
  },
  {
    code: "Armenia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/1280px-Flag_of_Armenia.svg.png",
    name: "Armenia",
    fullName: "Republic of Armenia",
    nameInNativeLang: "Հայաստանի Հանրապետություն",
    capitalCity: "Yerevan",
    largestCity: "Yerevan",
    officialLanguages: "Armenian",
    religion: "Christianity",
    population: "2,889,000",
    rankByPopulation: "138",
    independence: "21-Sep-1991",
    area: "29,743",
    currency: "Armenian Dram (AMD)",
  },
  {
    code: "Australia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/800px-Flag_of_Australia.svg.png",
    name: "Australia",
    fullName: "Commonwealth of Australia",
    nameInNativeLang: "Commonwealth of Australia",
    capitalCity: "Canberra",
    largestCity: "Sydney",
    officialLanguages: "English",
    religion: "Christianity",
    population: "25,739,200",
    rankByPopulation: "55",
    independence: "01-Jan-1901",
    area: "7,692,024",
    currency: "Australian Dollar (AUD)",
  },
  {
    code: "Austria",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/800px-Flag_of_Austria.svg.png",
    name: "Austria",
    fullName: "Republic of Austria",
    nameInNativeLang: "Republik Österreich",
    capitalCity: "Vienna",
    largestCity: "Vienna",
    officialLanguages: "German",
    religion: "Christianity",
    population: "9,006,398",
    rankByPopulation: "94",
    independence: "27-Oct-1955",
    area: "83,879",
    currency: "Euro (EUR)",
  },
  {
    code: "Azerbaijan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/800px-Flag_of_Azerbaijan.svg.png",
    name: "Azerbaijan",
    fullName: "Republic of Azerbaijan",
    nameInNativeLang: "Azərbaycan Respublikası",
    capitalCity: "Baku",
    largestCity: "Baku",
    officialLanguages: "Azerbaijani",
    religion: "Islam",
    population: "10,229,000",
    rankByPopulation: "89",
    independence: "30-Aug-1991",
    area: "86,600",
    currency: "Azerbaijani Manat (AZN)",
  },
  {
    code: "Bahamas",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/1280px-Flag_of_the_Bahamas.svg.png",
    name: "Bahamas",
    fullName: "Commonwealth of the Bahamas",
    nameInNativeLang: "Commonwealth of The Bahamas",
    capitalCity: "Nassau",
    largestCity: "Nassau",
    officialLanguages: "English",
    religion: "Christianity",
    population: "400,516",
    rankByPopulation: "173",
    independence: "10-Jul-1973",
    area: "13,880",
    currency: "Bahamian Dollar (BSD)",
  },
  {
    code: "Bahrain",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/1024px-Flag_of_Bahrain.svg.png",
    name: "Bahrain",
    fullName: "Kingdom of Bahrain",
    nameInNativeLang: "مملكة البحرين",
    capitalCity: "Manama",
    largestCity: "Manama",
    officialLanguages: "Arabic",
    religion: "Islam",
    population: "1,701,575",
    rankByPopulation: "140",
    independence: "15-Aug-1971",
    area: "765",
    currency: "Bahraini Dinar (BHD)",
  },
  {
    code: "Bangladesh",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/800px-Flag_of_Bangladesh.svg.png",
    name: "Bangladesh",
    fullName: "People's Republic of Bangladesh",
    nameInNativeLang: "বাংলাদেশ",
    capitalCity: "Dhaka",
    largestCity: "Dhaka",
    officialLanguages: "Bengali",
    religion: "Islam",
    population: "166,303,498",
    rankByPopulation: "8",
    independence: "26-Mar-1971",
    area: "147,570",
    currency: "Bangladeshi Taka (BDT)",
  },
  {
    code: "Barbados",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/800px-Flag_of_Barbados.svg.png",
    name: "Barbados",
    fullName: "Barbados",
    nameInNativeLang: "Barbados",
    capitalCity: "Bridgetown",
    largestCity: "Bridgetown",
    officialLanguages: "English",
    religion: "Christianity",
    population: "287,025",
    rankByPopulation: "177",
    independence: "30-Nov-1966",
    area: "430",
    currency: "Barbadian Dollar (BBD)",
  },
  {
    code: "Belgium",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/800px-Flag_of_Belgium.svg.png",
    name: "Belgium",
    fullName: "Kingdom of Belgium",
    nameInNativeLang: "Royaume de Belgique",
    capitalCity: "Brussels",
    largestCity: "Brussels",
    officialLanguages: "Dutch, French, German",
    religion: "Christianity",
    population: "11,590,000",
    rankByPopulation: "81",
    independence: "21-Jul-1831",
    area: "30,528",
    currency: "Euro (EUR)",
  },
  {
    code: "Belize",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/800px-Flag_of_Belize.svg.png",
    name: "Belize",
    fullName: "Belize",
    nameInNativeLang: "Belize",
    capitalCity: "Belmopan",
    largestCity: "Belize City",
    officialLanguages: "English",
    religion: "Christianity",
    population: "419,199",
    rankByPopulation: "165",
    independence: "21-Sep-1981",
    area: "22,966",
    currency: "Belize Dollar (BZD)",
  },
  {
    code: "Benin",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/800px-Flag_of_Benin.svg.png",
    name: "Benin",
    fullName: "Republic of Benin",
    nameInNativeLang: "République du Bénin",
    capitalCity: "Porto-Novo",
    largestCity: "Cotonou",
    officialLanguages: "French",
    religion: "Vodun, Christianity, Islam",
    population: "12,123,200",
    rankByPopulation: "87",
    independence: "01-Aug-1960",
    area: "112,622",
    currency: "West African CFA Franc (XOF)",
  },
  {
    code: "Bhutan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/800px-Flag_of_Bhutan.svg.png",
    name: "Bhutan",
    fullName: "Kingdom of Bhutan",
    nameInNativeLang: "འབྲུག",
    capitalCity: "Thimphu",
    largestCity: "Thimphu",
    officialLanguages: "Dzongkha",
    religion: "Buddhism",
    population: "779,000",
    rankByPopulation: "170",
    independence: "17-Dec-1907",
    area: "38,394",
    currency: "Bhutanese Ngultrum (BTN)",
  },
  {
    code: "Bolivia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/800px-Flag_of_Bolivia.svg.png",
    name: "Bolivia",
    fullName: "Plurinational State of Bolivia",
    nameInNativeLang: "Estado Plurinacional de Bolivia",
    capitalCity: "Sucre",
    largestCity: "Santa Cruz de la Sierra",
    officialLanguages: "Spanish, Quechua, Aymara, Guarani",
    religion: "Christianity",
    population: "11,634,000",
    rankByPopulation: "90",
    independence: "06-Aug-1825",
    area: "1,098,581",
    currency: "Bolivian Boliviano (BOB)",
  },
  {
    code: "Bosnia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/1280px-Flag_of_Bosnia_and_Herzegovina.svg.png",
    name: "Bosnia",
    fullName: "Bosnia and Herzegovina",
    nameInNativeLang: "Босна и Херцеговина",
    capitalCity: "Sarajevo",
    largestCity: "Sarajevo",
    officialLanguages: "Bosnian, Croatian, Serbian",
    religion: "Islam, Christianity",
    population: "3,301,000",
    rankByPopulation: "126",
    independence: "01-Mar-1992",
    area: "51,197",
    currency: "Bosnia and Herzegovina Convertible Mark (BAM)",
  },
  {
    code: "Botswana",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/800px-Flag_of_Botswana.svg.png",
    name: "Botswana",
    fullName: "Republic of Botswana",
    nameInNativeLang: "Republic of Botswana",
    capitalCity: "Gaborone",
    largestCity: "Gaborone",
    officialLanguages: "English, Setswana",
    religion: "Christianity",
    population: "2,351,627",
    rankByPopulation: "145",
    independence: "30-Sep-1966",
    area: "581,730",
    currency: "Botswana Pula (BWP)",
  },
  {
    code: "Brazil",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/800px-Flag_of_Brazil.svg.png",
    name: "Brazil",
    fullName: "Federative Republic of Brazil",
    nameInNativeLang: "República Federativa do Brasil",
    capitalCity: "Brasília",
    largestCity: "São Paulo",
    officialLanguages: "Portuguese",
    religion: "Christianity",
    population: "213,993,437",
    rankByPopulation: "6",
    independence: "07-Sep-1822",
    area: "8,515,767",
    currency: "Brazilian Real (BRL)",
  },
  {
    code: "Brunei",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/800px-Flag_of_Brunei.svg.png",
    name: "Brunei",
    fullName: "Negara Brunei Darussalam",
    nameInNativeLang: "Negara Brunei Darussalam",
    capitalCity: "Bandar Seri Begawan",
    largestCity: "Bandar Seri Begawan",
    officialLanguages: "Malay",
    religion: "Islam",
    population: "453,600",
    rankByPopulation: "171",
    independence: "01-Jan-1984",
    area: "5,765",
    currency: "Brunei Dollar (BND)",
  },
  {
    code: "Bulgaria",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/800px-Flag_of_Bulgaria.svg.png",
    name: "Bulgaria",
    fullName: "Republic of Bulgaria",
    nameInNativeLang: "Република България",
    capitalCity: "Sofia",
    largestCity: "Sofia",
    officialLanguages: "Bulgarian",
    religion: "Eastern Orthodox",
    population: "6,951,482",
    rankByPopulation: "108",
    independence: "03-Mar-1908",
    area: "110,879",
    currency: "Bulgarian Lev (BGN)",
  },
  {
    code: "Burkina-faso",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/800px-Flag_of_Burkina_Faso.svg.png",
    name: "Burkina Faso",
    fullName: "Burkina Faso",
    nameInNativeLang: "Burkina Faso",
    capitalCity: "Ouagadougou",
    largestCity: "Ouagadougou",
    officialLanguages: "French",
    religion: "Islam, Christianity, Traditional",
    population: "22,015,000",
    rankByPopulation: "61",
    independence: "05-Aug-1960",
    area: "272,967",
    currency: "West African CFA Franc (XOF)",
  },
  {
    code: "Burundi",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/800px-Flag_of_Burundi.svg.png",
    name: "Burundi",
    fullName: "Republic of Burundi",
    nameInNativeLang: "Republika y'u Burundi",
    capitalCity: "Gitega",
    largestCity: "Bujumbura",
    officialLanguages: "Kirundi, French, English",
    religion: "Christianity",
    population: "12,170,000",
    rankByPopulation: "86",
    independence: "01-Jul-1962",
    area: "27,834",
    currency: "Burundian Franc (BIF)",
  },
  {
    code: "Cabo-Verde",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/1024px-Flag_of_Cape_Verde.svg.png",
    name: "Cabo Verde",
    fullName: "Republic of Cabo Verde",
    nameInNativeLang: "República de Cabo Verde",
    capitalCity: "Praia",
    largestCity: "Praia",
    officialLanguages: "Portuguese",
    religion: "Christianity",
    population: "550,000",
    rankByPopulation: "174",
    independence: "05-Jul-1975",
    area: "4,033",
    currency: "Cape Verdean Escudo (CVE)",
  },
  {
    code: "Cameroon",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/800px-Flag_of_Cameroon.svg.png",
    name: "Cameroon",
    fullName: "Republic of Cameroon",
    nameInNativeLang: "République du Cameroun",
    capitalCity: "Yaoundé",
    largestCity: "Douala",
    officialLanguages: "French, English",
    religion: "Christianity, Traditional",
    population: "27,198,000",
    rankByPopulation: "67",
    independence: "01-Jan-1960",
    area: "475,442",
    currency: "Central African CFA Franc (XAF)",
  },
  {
    code: "Canada",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/800px-Flag_of_Canada.svg.png",
    name: "Canada",
    fullName: "Canada",
    nameInNativeLang: "Canada",
    capitalCity: "Ottawa",
    largestCity: "Toronto",
    officialLanguages: "English, French",
    religion: "Christianity",
    population: "38,654,000",
    rankByPopulation: "39",
    independence: "01-Jul-1867",
    area: "9,984,670",
    currency: "Canadian Dollar (CAD)",
  },
  {
    code: "Central-African",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/800px-Flag_of_the_Central_African_Republic.svg.png",
    name: "Central African",
    fullName: "Central African Republic",
    nameInNativeLang: "République Centrafricaine",
    capitalCity: "Bangui",
    largestCity: "Bangui",
    officialLanguages: "Sango, French",
    religion: "Christianity, Traditional",
    population: "5,452,000",
    rankByPopulation: "123",
    independence: "13-Aug-1960",
    area: "622,984",
    currency: "Central African CFA Franc (XAF)",
  },
  {
    code: "Chad",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/800px-Flag_of_Chad.svg.png",
    name: "Chad",
    fullName: "Republic of Chad",
    nameInNativeLang: "جمهورية تشاد",
    capitalCity: "N'Djamena",
    largestCity: "N'Djamena",
    officialLanguages: "French, Arabic",
    religion: "Islam, Christianity",
    population: "17,200,000",
    rankByPopulation: "80",
    independence: "11-Aug-1960",
    area: "1,284,000",
    currency: "Central African CFA Franc (XAF)",
  },
  {
    code: "Chile",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/800px-Flag_of_Chile.svg.png",
    name: "Chile",
    fullName: "Republic of Chile",
    nameInNativeLang: "República de Chile",
    capitalCity: "Santiago",
    largestCity: "Santiago",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "19,049,000",
    rankByPopulation: "63",
    independence: "18-Sep-1810",
    area: "756,102",
    currency: "Chilean Peso (CLP)",
  },
  {
    code: "China",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/800px-Flag_of_the_People%27s_Republic_of_China.svg.png",
    name: "China",
    fullName: "People's Republic of China",
    nameInNativeLang: "中华人民共和国",
    capitalCity: "Beijing",
    largestCity: "Shanghai",
    officialLanguages: "Mandarin",
    religion: "Buddhism, Taoism, Christianity, Islam",
    population: "1,412,600,000",
    rankByPopulation: "1",
    independence: "01-Oct-1949",
    area: "9,596,961",
    currency: "Renminbi (CNY)",
  },
  {
    code: "Colombia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/800px-Flag_of_Colombia.svg.png",
    name: "Colombia",
    fullName: "Republic of Colombia",
    nameInNativeLang: "República de Colombia",
    capitalCity: "Bogotá",
    largestCity: "Bogotá",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "51,074,000",
    rankByPopulation: "28",
    independence: "20-Jul-1810",
    area: "1,141,748",
    currency: "Colombian Peso (COP)",
  },
  {
    code: "Comoros",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/1024px-Flag_of_the_Comoros.svg.png",
    name: "Comoros",
    fullName: "Union of the Comoros",
    nameInNativeLang: "Union des Comores",
    capitalCity: "Moroni",
    largestCity: "Moroni",
    officialLanguages: "Arabic, French, Comorian",
    religion: "Islam",
    population: "806,153",
    rankByPopulation: "173",
    independence: "06-Jul-1975",
    area: "2,235",
    currency: "Comorian Franc (KMF)",
  },
  {
    code: "Congo",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/800px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png",
    name: "Congo",
    fullName: "Republic of the Congo",
    nameInNativeLang: "République du Congo",
    capitalCity: "Brazzaville",
    largestCity: "Brazzaville",
    officialLanguages: "French, Lingala",
    religion: "Christianity",
    population: "5,200,000",
    rankByPopulation: "124",
    independence: "15-Aug-1960",
    area: "342,000",
    currency: "Central African CFA Franc (XAF)",
  },
  {
    code: "Croatia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/800px-Flag_of_Croatia.svg.png",
    name: "Croatia",
    fullName: "Republic of Croatia",
    nameInNativeLang: "Republika Hrvatska",
    capitalCity: "Zagreb",
    largestCity: "Zagreb",
    officialLanguages: "Croatian",
    religion: "Christianity",
    population: "4,036,355",
    rankByPopulation: "126",
    independence: "25-Jun-1991",
    area: "56,594",
    currency: "Croatian Kuna (HRK)",
  },
  {
    code: "Cuba",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/1280px-Flag_of_Cuba.svg.png",
    name: "Cuba",
    fullName: "Republic of Cuba",
    nameInNativeLang: "República de Cuba",
    capitalCity: "Havana",
    largestCity: "Havana",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "11,226,000",
    rankByPopulation: "89",
    independence: "20-May-1902",
    area: "109,884",
    currency: "Cuban Peso (CUP)",
  },
  {
    code: "Cyprus",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/800px-Flag_of_Cyprus.svg.png",
    name: "Cyprus",
    fullName: "Republic of Cyprus",
    nameInNativeLang: "Κυπριακή Δημοκρατία",
    capitalCity: "Nicosia",
    largestCity: "Nicosia",
    officialLanguages: "Greek, Turkish",
    religion: "Christianity",
    population: "1,218,000",
    rankByPopulation: "160",
    independence: "16-Aug-1960",
    area: "9,251",
    currency: "Euro (EUR)",
  },
  {
    code: "Czech",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/800px-Flag_of_the_Czech_Republic.svg.png",
    name: "Czech Republic",
    fullName: "Czech Republic",
    nameInNativeLang: "Česká republika",
    capitalCity: "Prague",
    largestCity: "Prague",
    officialLanguages: "Czech",
    religion: "Christianity",
    population: "10,689,000",
    rankByPopulation: "83",
    independence: "28-Oct-1918",
    area: "78,865",
    currency: "Czech Koruna (CZK)",
  },
  {
    code: "Denmark",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/800px-Flag_of_Denmark.svg.png",
    name: "Denmark",
    fullName: "Kingdom of Denmark",
    nameInNativeLang: "Kongeriget Danmark",
    capitalCity: "Copenhagen",
    largestCity: "Copenhagen",
    officialLanguages: "Danish",
    religion: "Christianity",
    population: "5,840,000",
    rankByPopulation: "119",
    independence: "05-Jun-1849",
    area: "43,094",
    currency: "Danish Krone (DKK)",
  },
  {
    code: "Djibouti",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/800px-Flag_of_Djibouti.svg.png",
    name: "Djibouti",
    fullName: "Republic of Djibouti",
    nameInNativeLang: "جمهورية جيبوتي",
    capitalCity: "Djibouti",
    largestCity: "Djibouti",
    officialLanguages: "French, Arabic",
    religion: "Islam",
    population: "883,000",
    rankByPopulation: "170",
    independence: "27-Jun-1977",
    area: "23,200",
    currency: "Djiboutian Franc (DJF)",
  },
  {
    code: "Dominican",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/800px-Flag_of_the_Dominican_Republic.svg.png",
    name: "Dominican Republic",
    fullName: "Dominican Republic",
    nameInNativeLang: "República Dominicana",
    capitalCity: "Santo Domingo",
    largestCity: "Santo Domingo",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "11,110,000",
    rankByPopulation: "92",
    independence: "27-Feb-1844",
    area: "48,671",
    currency: "Dominican Peso (DOP)",
  },

  {
    code: "Ecuador",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/800px-Flag_of_Ecuador.svg.png",
    name: "Ecuador",
    fullName: "Republic of Ecuador",
    nameInNativeLang: "República del Ecuador",
    capitalCity: "Quito",
    largestCity: "Guayaquil",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "17,610,000",
    rankByPopulation: "73",
    independence: "24-May-1822",
    area: "256,370",
    currency: "United States Dollar (USD)",
  },
  {
    code: "Egypt",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/800px-Flag_of_Egypt.svg.png",
    name: "Egypt",
    fullName: "Arab Republic of Egypt",
    nameInNativeLang: "جمهورية مصر العربية",
    capitalCity: "Cairo",
    largestCity: "Cairo",
    officialLanguages: "Arabic",
    religion: "Islam",
    population: "105,000,000",
    rankByPopulation: "3",
    independence: "28-Feb-1922",
    area: "1,001,450",
    currency: "Egyptian Pound (EGP)",
  },
  {
    code: "El-Salvador",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/1024px-Flag_of_El_Salvador.svg.png",
    name: "El Salvador",
    fullName: "Republic of El Salvador",
    nameInNativeLang: "República de El Salvador",
    capitalCity: "San Salvador",
    largestCity: "San Salvador",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "6,524,000",
    rankByPopulation: "111",
    independence: "15-Sep-1821",
    area: "21,041",
    currency: "United States Dollar (USD)",
  },
  {
    code: "Eswatini",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/800px-Flag_of_Eswatini.svg.png",
    name: "Eswatini",
    fullName: "Kingdom of Eswatini",
    nameInNativeLang: "Umbuso weSwatini",
    capitalCity: "Mbabane",
    largestCity: "Mbabane",
    officialLanguages: "English, siSwati",
    religion: "Christianity",
    population: "1,200,000",
    rankByPopulation: "169",
    independence: "06-Sep-1968",
    area: "17,364",
    currency: "Swazi Lilangeni (SZL)",
  },
  {
    code: "Georgia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/800px-Flag_of_Georgia.svg.png",
    name: "Georgia",
    fullName: "Georgia",
    nameInNativeLang: "საქართველო",
    capitalCity: "Tbilisi",
    largestCity: "Tbilisi",
    officialLanguages: "Georgian",
    religion: "Orthodox Christianity",
    population: "3,710,000",
    rankByPopulation: "125",
    independence: "09-Apr-1991",
    area: "69,700",
    currency: "Georgian Lari (GEL)",
  },
  {
    code: "Germany",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.svg.png?20111003033442",
    name: "Germany",
    fullName: "Federal Republic of Germany",
    nameInNativeLang: "Bundesrepublik Deutschland",
    capitalCity: "Berlin",
    largestCity: "Berlin",
    officialLanguages: "German",
    religion: "Christianity",
    population: "83,129,000",
    rankByPopulation: "19",
    independence: "03-Oct-1990",
    area: "357,022",
    currency: "Euro (EUR)",
  },
  {
    code: "Ghana",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/800px-Flag_of_Ghana.svg.png",
    name: "Ghana",
    fullName: "Republic of Ghana",
    nameInNativeLang: "Republic of Ghana",
    capitalCity: "Accra",
    largestCity: "Accra",
    officialLanguages: "English",
    religion: "Christianity, Traditional",
    population: "32,830,000",
    rankByPopulation: "47",
    independence: "06-Mar-1957",
    area: "238,533",
    currency: "Ghanaian Cedi (GHS)",
  },
  {
    code: "Greece",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/800px-Flag_of_Greece.svg.png",
    name: "Greece",
    fullName: "Hellenic Republic",
    nameInNativeLang: "Ελληνική Δημοκρατία",
    capitalCity: "Athens",
    largestCity: "Athens",
    officialLanguages: "Greek",
    religion: "Christianity",
    population: "10,571,000",
    rankByPopulation: "81",
    independence: "25-Mar-1821",
    area: "131,957",
    currency: "Euro (EUR)",
  },
  {
    code: "Greenland",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/130px-Flag_of_Greenland.svg.png",
    name: "Greenland",
    fullName: "Greenland",
    nameInNativeLang: "Kalaallit Nunaat",
    capitalCity: "Nuuk",
    largestCity: "Nuuk",
    officialLanguages: "Greenlandic, Danish",
    religion: "Christianity",
    population: "56,000",
    rankByPopulation: "208",
    independence: "21-Jun-2009",
    area: "2,166,086",
    currency: "Danish Krone (DKK)",
  },
  {
    code: "Guam",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/1024px-Flag_of_Guam.svg.png",
    name: "Guam",
    fullName: "Guam",
    nameInNativeLang: "Guam",
    capitalCity: "Hagåtña",
    largestCity: "Dededo",
    officialLanguages: "English, Chamorro",
    religion: "Christianity",
    population: "173,000",
    rankByPopulation: "182",
    independence: "01-Jul-1950",
    area: "549",
    currency: "United States Dollar (USD)",
  },
  {
    code: "Ghana",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/800px-Flag_of_Ghana.svg.png",
    name: "Ghana",
    fullName: "Republic of Ghana",
    nameInNativeLang: "Republic of Ghana",
    capitalCity: "Accra",
    largestCity: "Accra",
    officialLanguages: "English",
    religion: "Christianity, Traditional",
    population: "32,830,000",
    rankByPopulation: "47",
    independence: "06-Mar-1957",
    area: "238,533",
    currency: "Ghanaian Cedi (GHS)",
  },

  {
    code: "Guatemala",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/800px-Flag_of_Guatemala.svg.png",
    name: "Guatemala",
    fullName: "Republic of Guatemala",
    nameInNativeLang: "República de Guatemala",
    capitalCity: "Guatemala City",
    largestCity: "Guatemala City",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "19,520,000",
    rankByPopulation: "61",
    independence: "15-Sep-1821",
    area: "108,889",
    currency: "Guatemalan Quetzal (GTQ)",
  },
  {
    code: "Guinea",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/800px-Flag_of_Guinea.svg.png",
    name: "Guinea",
    fullName: "Republic of Guinea",
    nameInNativeLang: "République de Guinée",
    capitalCity: "Conakry",
    largestCity: "Conakry",
    officialLanguages: "French",
    religion: "Islam, Christianity",
    population: "13,300,000",
    rankByPopulation: "92",
    independence: "02-Oct-1958",
    area: "245,857",
    currency: "Guinean Franc (GNF)",
  },

  {
    code: "Guinea-Bissau",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/1280px-Flag_of_Guinea-Bissau.svg.png",
    name: "Guinea-Bissau",
    fullName: "Republic of Guinea-Bissau",
    nameInNativeLang: "República da Guiné-Bissau",
    capitalCity: "Bissau",
    largestCity: "Bissau",
    officialLanguages: "Portuguese",
    religion: "Islam, Christianity",
    population: "2,017,000",
    rankByPopulation: "150",
    independence: "24-Sep-1973",
    area: "36,125",
    currency: "West African CFA Franc (XOF)",
  },
  {
    code: "Haiti",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/800px-Flag_of_Haiti.svg.png",
    name: "Haiti",
    fullName: "Republic of Haiti",
    nameInNativeLang: "République d'Haïti",
    capitalCity: "Port-au-Prince",
    largestCity: "Port-au-Prince",
    officialLanguages: "Haitian Creole, French",
    religion: "Christianity",
    population: "11,400,000",
    rankByPopulation: "90",
    independence: "01-Jan-1804",
    area: "27,750",
    currency: "Gourde (HTG)",
  },
  {
    code: "Honduras",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/125px-Flag_of_Honduras.svg.png",
    name: "Honduras",
    fullName: "Republic of Honduras",
    nameInNativeLang: "República de Honduras",
    capitalCity: "Tegucigalpa",
    largestCity: "Tegucigalpa",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "10,400,000",
    rankByPopulation: "97",
    independence: "15-Sep-1821",
    area: "112,492",
    currency: "Honduran Lempira (HNL)",
  },
  {
    code: "Hungary",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/800px-Flag_of_Hungary.svg.png",
    name: "Hungary",
    fullName: "Hungary",
    nameInNativeLang: "Magyarország",
    capitalCity: "Budapest",
    largestCity: "Budapest",
    officialLanguages: "Hungarian",
    religion: "Christianity",
    population: "9,682,000",
    rankByPopulation: "92",
    independence: "20-Aug-1000",
    area: "93,030",
    currency: "Hungarian Forint (HUF)",
  },
  {
    code: "Iceland",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/800px-Flag_of_Iceland.svg.png",
    name: "Iceland",
    fullName: "Republic of Iceland",
    nameInNativeLang: "Lýðveldið Ísland",
    capitalCity: "Reykjavik",
    largestCity: "Reykjavik",
    officialLanguages: "Icelandic",
    religion: "Christianity",
    population: "373,000",
    rankByPopulation: "177",
    independence: "17-Jun-1944",
    area: "103,000",
    currency: "Icelandic Króna (ISK)",
  },
  {
    code: "India",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/800px-Flag_of_India.svg.png",
    name: "India",
    fullName: "Republic of India",
    nameInNativeLang: "भारत गणराज्य",
    capitalCity: "New Delhi",
    largestCity: "Mumbai",
    officialLanguages: "Hindi, English",
    religion: "Hinduism, Islam, Christianity, Sikhism",
    population: "1,428,600,000",
    rankByPopulation: "2",
    independence: "15-Aug-1947",
    area: "3,287,263",
    currency: "Indian Rupee (INR)",
  },
  {
    code: "Indonesia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/800px-Flag_of_Indonesia.svg.png",
    name: "Indonesia",
    fullName: "Republic of Indonesia",
    nameInNativeLang: "Republik Indonesia",
    capitalCity: "Jakarta",
    largestCity: "Jakarta",
    officialLanguages: "Indonesian",
    religion: "Islam, Christianity, Hinduism, Buddhism",
    population: "275,122,000",
    rankByPopulation: "4",
    independence: "17-Aug-1945",
    area: "1,904,569",
    currency: "Indonesian Rupiah (IDR)",
  },
  {
    code: "Ireland",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/800px-Flag_of_Ireland.svg.png",
    name: "Ireland",
    fullName: "Ireland",
    nameInNativeLang: "Éire",
    capitalCity: "Dublin",
    largestCity: "Dublin",
    officialLanguages: "Irish, English",
    religion: "Christianity",
    population: "5,090,000",
    rankByPopulation: "122",
    independence: "06-Dec-1922",
    area: "70,273",
    currency: "Euro (EUR)",
  },
  {
    code: "Israel",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/800px-Flag_of_Israel.svg.png",
    name: "Israel",
    fullName: "State of Israel",
    nameInNativeLang: "מְדִינַת יִשְׂרָאֵל",
    capitalCity: "Jerusalem",
    largestCity: "Jerusalem",
    officialLanguages: "Hebrew, Arabic",
    religion: "Judaism, Christianity, Islam",
    population: "9,600,000",
    rankByPopulation: "104",
    independence: "14-May-1948",
    area: "22,072",
    currency: "Israeli New Shekel (ILS)",
  },
  {
    code: "Italy",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/800px-Flag_of_Italy.svg.png",
    name: "Italy",
    fullName: "Italian Republic",
    nameInNativeLang: "Repubblica Italiana",
    capitalCity: "Rome",
    largestCity: "Rome",
    officialLanguages: "Italian",
    religion: "Christianity",
    population: "58,900,000",
    rankByPopulation: "24",
    independence: "17-Mar-1861",
    area: "301,340",
    currency: "Euro (EUR)",
  },
  {
    code: "Jamaica",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/1280px-Flag_of_Jamaica.svg.png",
    name: "Jamaica",
    fullName: "Jamaica",
    nameInNativeLang: "Jamaica",
    capitalCity: "Kingston",
    largestCity: "Kingston",
    officialLanguages: "English",
    religion: "Christianity",
    population: "2,700,000",
    rankByPopulation: "151",
    independence: "06-Aug-1962",
    area: "10,991",
    currency: "Jamaican Dollar (JMD)",
  },
  {
    code: "Japan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/800px-Flag_of_Japan.svg.png",
    name: "Japan",
    fullName: "Japan",
    nameInNativeLang: "日本",
    capitalCity: "Tokyo",
    largestCity: "Tokyo",
    officialLanguages: "Japanese",
    religion: "Shinto, Buddhism",
    population: "125,800,000",
    rankByPopulation: "11",
    independence: "11-Feb-660 BC",
    area: "377,975",
    currency: "Japanese Yen (JPY)",
  },
  {
    code: "Jordan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/1280px-Flag_of_Jordan.svg.png",
    name: "Jordan",
    fullName: "Hashemite Kingdom of Jordan",
    nameInNativeLang: "المملكة الأردنية الهاشمية",
    capitalCity: "Amman",
    largestCity: "Amman",
    officialLanguages: "Arabic",
    religion: "Islam, Christianity",
    population: "10,500,000",
    rankByPopulation: "95",
    independence: "25-May-1946",
    area: "89,342",
    currency: "Jordanian Dinar (JOD)",
  },
  {
    code: "Kazakhstan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/800px-Flag_of_Kazakhstan.svg.png",
    name: "Kazakhstan",
    fullName: "Republic of Kazakhstan",
    nameInNativeLang: "Қазақстан Республикасы",
    capitalCity: "Astana",
    largestCity: "Almaty",
    officialLanguages: "Kazakh, Russian",
    religion: "Islam, Christianity",
    population: "19,300,000",
    rankByPopulation: "61",
    independence: "16-Dec-1991",
    area: "2,724,900",
    currency: "Kazakhstani Tenge (KZT)",
  },
  {
    code: "Kenya",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/800px-Flag_of_Kenya.svg.png",
    name: "Kenya",
    fullName: "Republic of Kenya",
    nameInNativeLang: "Jamhuri ya Kenya",
    capitalCity: "Nairobi",
    largestCity: "Nairobi",
    officialLanguages: "Swahili, English",
    religion: "Christianity, Traditional",
    population: "54,400,000",
    rankByPopulation: "29",
    independence: "12-Dec-1963",
    area: "580,367",
    currency: "Kenyan Shilling (KES)",
  },
  {
    code: "Kiribati",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/800px-Flag_of_Kiribati.svg.png",
    name: "Kiribati",
    fullName: "Republic of Kiribati",
    nameInNativeLang: "Te I-Kiribati",
    capitalCity: "South Tarawa",
    largestCity: "South Tarawa",
    officialLanguages: "Gilbertese",
    religion: "Christianity",
    population: "120,000",
    rankByPopulation: "205",
    independence: "12-Jul-1979",
    area: "811",
    currency: "Australian Dollar (AUD)",
  },
  {
    code: "Kosovo",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Kosovo.svg/800px-Flag_of_Kosovo.svg.png",
    name: "Kosovo",
    fullName: "Republic of Kosovo",
    nameInNativeLang: "Republika e Kosovës",
    capitalCity: "Pristina",
    largestCity: "Pristina",
    officialLanguages: "Albanian, Serbian",
    religion: "Islam, Christianity",
    population: "1,810,000",
    rankByPopulation: "157",
    independence: "17-Feb-2008",
    area: "10,887",
    currency: "Euro (EUR)",
  },
  {
    code: "Kuwait",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/1280px-Flag_of_Kuwait.svg.png",
    name: "Kuwait",
    fullName: "State of Kuwait",
    nameInNativeLang: "دولة الكويت",
    capitalCity: "Kuwait City",
    largestCity: "Kuwait City",
    officialLanguages: "Arabic",
    religion: "Islam",
    population: "4,600,000",
    rankByPopulation: "131",
    independence: "19-Jun-1961",
    area: "17,818",
    currency: "Kuwaiti Dinar (KWD)",
  },
  {
    code: "Laos",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/125px-Flag_of_Laos.svg.png",
    name: "Laos",
    fullName: "Lao People's Democratic Republic",
    nameInNativeLang: "ສປປ ແລວສ",
    capitalCity: "Vientiane",
    largestCity: "Vientiane",
    officialLanguages: "Lao",
    religion: "Buddhism",
    population: "7,300,000",
    rankByPopulation: "115",
    independence: "19-Jul-1949",
    area: "236,800",
    currency: "Lao Kip (LAK)",
  },
  {
    code: "Lebanon",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/800px-Flag_of_Lebanon.svg.png",
    name: "Lebanon",
    fullName: "Lebanese Republic",
    nameInNativeLang: "جمهورية لبنان",
    capitalCity: "Beirut",
    largestCity: "Beirut",
    officialLanguages: "Arabic",
    religion: "Islam, Christianity",
    population: "6,100,000",
    rankByPopulation: "126",
    independence: "22-Nov-1943",
    area: "10,452",
    currency: "Lebanese Pound (LBP)",
  },
  {
    code: "Lesotho",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/800px-Flag_of_Lesotho.svg.png",
    name: "Lesotho",
    fullName: "Kingdom of Lesotho",
    nameInNativeLang: "Lesotho",
    capitalCity: "Maseru",
    largestCity: "Maseru",
    officialLanguages: "Sesotho, English",
    religion: "Christianity",
    population: "2,230,000",
    rankByPopulation: "155",
    independence: "04-Oct-1966",
    area: "30,355",
    currency: "Lesotho Loti (LSL)",
  },
  {
    code: "Liechtenstein",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/1024px-Flag_of_Liechtenstein.svg.png",
    name: "Liechtenstein",
    fullName: "Principality of Liechtenstein",
    nameInNativeLang: "Fürstentum Liechtenstein",
    capitalCity: "Vaduz",
    largestCity: "Schaan",
    officialLanguages: "German",
    religion: "Christianity",
    population: "39,000",
    rankByPopulation: "197",
    independence: "23-Jan-1719",
    area: "160",
    currency: "Swiss Franc (CHF)",
  },
  {
    code: "Lithuania",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/1024px-Flag_of_Lithuania.svg.png",
    name: "Lithuania",
    fullName: "Republic of Lithuania",
    nameInNativeLang: "Lietuva",
    capitalCity: "Vilnius",
    largestCity: "Vilnius",
    officialLanguages: "Lithuanian",
    religion: "Christianity",
    population: "2,700,000",
    rankByPopulation: "151",
    independence: "11-Mar-1990",
    area: "65,300",
    currency: "Euro (EUR)",
  },
  {
    code: "Luxembourg",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/800px-Flag_of_Luxembourg.svg.png",
    name: "Luxembourg",
    fullName: "Grand Duchy of Luxembourg",
    nameInNativeLang: "Grand-Duché de Luxembourg",
    capitalCity: "Luxembourg City",
    largestCity: "Luxembourg City",
    officialLanguages: "Luxembourgish, French, German",
    religion: "Christianity",
    population: "645,000",
    rankByPopulation: "176",
    independence: "23-Jun-1867",
    area: "2,586",
    currency: "Euro (EUR)",
  },
  {
    code: "Morocco",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/800px-Flag_of_Morocco.svg.png",
    name: "Morocco",
    fullName: "Kingdom of Morocco",
    nameInNativeLang: "المملكة المغربية",
    capitalCity: "Rabat",
    largestCity: "Casablanca",
    officialLanguages: "Arabic, Amazigh",
    religion: "Islam",
    population: "37,000,000",
    rankByPopulation: "40",
    independence: "02-Mar-1956",
    area: "446,550",
    currency: "Moroccan Dirham (MAD)",
  },
  {
    code: "Moldova",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/125px-Flag_of_Moldova.svg.png",
    name: "Moldova",
    fullName: "Republic of Moldova",
    nameInNativeLang: "Republica Moldova",
    capitalCity: "Chișinău",
    largestCity: "Chișinău",
    officialLanguages: "Romanian",
    religion: "Christianity",
    population: "2,600,000",
    rankByPopulation: "157",
    independence: "27-Aug-1991",
    area: "33,846",
    currency: "Moldovan Leu (MDL)",
  },
  {
    code: "Mexico",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/800px-Flag_of_Mexico.svg.png",
    name: "Mexico",
    fullName: "United Mexican States",
    nameInNativeLang: "Estados Unidos Mexicanos",
    capitalCity: "Mexico City",
    largestCity: "Mexico City",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "126,200,000",
    rankByPopulation: "10",
    independence: "16-Sep-1810",
    area: "1,964,375",
    currency: "Mexican Peso (MXN)",
  },
  {
    code: "Malaysia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/800px-Flag_of_Malaysia.svg.png",
    name: "Malaysia",
    fullName: "Federation of Malaysia",
    nameInNativeLang: "Persekutuan Malaysia",
    capitalCity: "Kuala Lumpur",
    largestCity: "Kuala Lumpur",
    officialLanguages: "Malay",
    religion: "Islam, Buddhism, Christianity, Hinduism",
    population: "33,400,000",
    rankByPopulation: "46",
    independence: "31-Aug-1957",
    area: "330,803",
    currency: "Malaysian Ringgit (MYR)",
  },
  {
    code: "Namibia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/800px-Flag_of_Namibia.svg.png",
    name: "Namibia",
    fullName: "Republic of Namibia",
    nameInNativeLang: "Republic of Namibia",
    capitalCity: "Windhoek",
    largestCity: "Windhoek",
    officialLanguages: "English",
    religion: "Christianity",
    population: "2,700,000",
    rankByPopulation: "151",
    independence: "21-Mar-1990",
    area: "825,615",
    currency: "Namibian Dollar (NAD)",
  },

  {
    code: "Nigeria",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/1280px-Flag_of_Nigeria.svg.png",
    name: "Nigeria",
    fullName: "Federal Republic of Nigeria",
    nameInNativeLang: "Federal Republic of Nigeria",
    capitalCity: "Abuja",
    largestCity: "Lagos",
    officialLanguages: "English",
    religion: "Islam, Christianity, Traditional",
    population: "223,800,000",
    rankByPopulation: "7",
    independence: "01-Oct-1960",
    area: "923,769",
    currency: "Nigerian Naira (NGN)",
  },
  {
    code: "Netherlands",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/800px-Flag_of_the_Netherlands.svg.png",
    name: "Netherlands",
    fullName: "Kingdom of the Netherlands",
    nameInNativeLang: "Koninkrijk der Nederlanden",
    capitalCity: "Amsterdam",
    largestCity: "Amsterdam",
    officialLanguages: "Dutch",
    religion: "Christianity",
    population: "17,500,000",
    rankByPopulation: "66",
    independence: "26-Jul-1581",
    area: "41,543",
    currency: "Euro (EUR)",
  },
  {
    code: "New-Zealand",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/1280px-Flag_of_New_Zealand.svg.png",
    name: "New Zealand",
    fullName: "New Zealand",
    nameInNativeLang: "Aotearoa",
    capitalCity: "Wellington",
    largestCity: "Auckland",
    officialLanguages: "English, Māori",
    religion: "Christianity",
    population: "5,050,000",
    rankByPopulation: "125",
    independence: "26-Sep-1907",
    area: "268,021",
    currency: "New Zealand Dollar (NZD)",
  },
  {
    code: "Nicaragua",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/1024px-Flag_of_Nicaragua.svg.png",
    name: "Nicaragua",
    fullName: "Republic of Nicaragua",
    nameInNativeLang: "República de Nicaragua",
    capitalCity: "Managua",
    largestCity: "Managua",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "6,400,000",
    rankByPopulation: "121",
    independence: "15-Sep-1821",
    area: "130,373",
    currency: "Nicaraguan Córdoba (NIO)",
  },
  {
    code: "Norway",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/800px-Flag_of_Norway.svg.png",
    name: "Norway",
    fullName: "Kingdom of Norway",
    nameInNativeLang: "Norge",
    capitalCity: "Oslo",
    largestCity: "Oslo",
    officialLanguages: "Norwegian",
    religion: "Christianity",
    population: "5,450,000",
    rankByPopulation: "119",
    independence: "07-Jun-1905",
    area: "323,802",
    currency: "Norwegian Krone (NOK)",
  },
  {
    code: "Pakistan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/800px-Flag_of_Pakistan.svg.png",
    name: "Pakistan",
    fullName: "Islamic Republic of Pakistan",
    nameInNativeLang: "پاکستان",
    capitalCity: "Islamabad",
    largestCity: "Karachi",
    officialLanguages: "Urdu, English",
    religion: "Islam",
    population: "241,500,000",
    rankByPopulation: "5",
    independence: "14-Aug-1947",
    area: "881,913",
    currency: "Pakistani Rupee (PKR)",
  },
  {
    code: "Panama",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/800px-Flag_of_Panama.svg.png",
    name: "Panama",
    fullName: "Republic of Panama",
    nameInNativeLang: "República de Panamá",
    capitalCity: "Panama City",
    largestCity: "Panama City",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "4,500,000",
    rankByPopulation: "137",
    independence: "03-Nov-1903",
    area: "75,417",
    currency: "Panamanian Balboa (PAB)",
  },
  {
    code: "Peru",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/800px-Flag_of_Peru.svg.png",
    name: "Peru",
    fullName: "Republic of Peru",
    nameInNativeLang: "República del Perú",
    capitalCity: "Lima",
    largestCity: "Lima",
    officialLanguages: "Spanish, Quechua, Aymara",
    religion: "Christianity",
    population: "34,600,000",
    rankByPopulation: "48",
    independence: "28-Jul-1821",
    area: "1,285,216",
    currency: "Peruvian Sol (PEN)",
  },
  {
    code: "Philippines",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/800px-Flag_of_the_Philippines.svg.png",
    name: "Philippines",
    fullName: "Republic of the Philippines",
    nameInNativeLang: "Republika ng Pilipinas",
    capitalCity: "Manila",
    largestCity: "Quezon City",
    officialLanguages: "Filipino, English",
    religion: "Christianity",
    population: "113,900,000",
    rankByPopulation: "13",
    independence: "12-Jun-1898",
    area: "300,000",
    currency: "Philippine Peso (PHP)",
  },
  {
    code: "Poland",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1024px-Flag_of_Poland.svg.png",
    name: "Poland",
    fullName: "Republic of Poland",
    nameInNativeLang: "Rzeczpospolita Polska",
    capitalCity: "Warsaw",
    largestCity: "Warsaw",
    officialLanguages: "Polish",
    religion: "Christianity",
    population: "37,600,000",
    rankByPopulation: "39",
    independence: "11-Nov-1918",
    area: "312,696",
    currency: "Polish Zloty (PLN)",
  },
  {
    code: "Portugal",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/800px-Flag_of_Portugal.svg.png",
    name: "Portugal",
    fullName: "Portuguese Republic",
    nameInNativeLang: "República Portuguesa",
    capitalCity: "Lisbon",
    largestCity: "Lisbon",
    officialLanguages: "Portuguese",
    religion: "Christianity",
    population: "10,300,000",
    rankByPopulation: "97",
    independence: "01-Dec-1640",
    area: "92,212",
    currency: "Euro (EUR)",
  },
  {
    code: "Qatar",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/800px-Flag_of_Qatar.svg.png",
    name: "Qatar",
    fullName: "State of Qatar",
    nameInNativeLang: "دولة قطر",
    capitalCity: "Doha",
    largestCity: "Doha",
    officialLanguages: "Arabic",
    religion: "Islam",
    population: "2,800,000",
    rankByPopulation: "150",
    independence: "03-Sep-1971",
    area: "11,586",
    currency: "Qatari Rial (QAR)",
  },
  {
    code: "Romania",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/600px-Flag_of_Romania.svg.png",
    name: "Romania",
    fullName: "Romania",
    nameInNativeLang: "România",
    capitalCity: "Bucharest",
    largestCity: "Bucharest",
    officialLanguages: "Romanian",
    religion: "Christianity",
    population: "19,500,000",
    rankByPopulation: "61",
    independence: "09-May-1877",
    area: "238,397",
    currency: "Romanian Leu (RON)",
  },
  {
    code: "Russia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/800px-Flag_of_Russia.svg.png",
    name: "Russia",
    fullName: "Russian Federation",
    nameInNativeLang: "Российская Федерация",
    capitalCity: "Moscow",
    largestCity: "Moscow",
    officialLanguages: "Russian",
    religion: "Christianity",
    population: "145,800,000",
    rankByPopulation: "9",
    independence: "12-Jun-1990",
    area: "17,098,242",
    currency: "Russian Ruble (RUB)",
  },
  {
    code: "Rwanda",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/800px-Flag_of_Rwanda.svg.png",
    name: "Rwanda",
    fullName: "Republic of Rwanda",
    nameInNativeLang: "Republic of Rwanda",
    capitalCity: "Kigali",
    largestCity: "Kigali",
    officialLanguages: "Kinyarwanda, French, English",
    religion: "Christianity",
    population: "13,400,000",
    rankByPopulation: "59",
    independence: "01-Jul-1962",
    area: "26,338",
    currency: "Rwandan Franc (RWF)",
  },
  {
    code: "KSA",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/800px-Flag_of_Saudi_Arabia.svg.png",
    name: "Saudi Arabia",
    fullName: "Kingdom of Saudi Arabia",
    nameInNativeLang: "المملكة العربية السعودية",
    capitalCity: "Riyadh",
    largestCity: "Riyadh",
    officialLanguages: "Arabic",
    religion: "Islam",
    population: "36,600,000",
    rankByPopulation: "41",
    independence: "23-Sep-1932",
    area: "2,149,690",
    currency: "Saudi Riyal (SAR)",
  },
  {
    code: "Senegal",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/800px-Flag_of_Senegal.svg.png",
    name: "Senegal",
    fullName: "Republic of Senegal",
    nameInNativeLang: "République du Sénégal",
    capitalCity: "Dakar",
    largestCity: "Dakar",
    officialLanguages: "French",
    religion: "Islam",
    population: "17,200,000",
    rankByPopulation: "67",
    independence: "04-Apr-1960",
    area: "196,722",
    currency: "West African CFA franc (XOF)",
  },
  {
    code: "Singapore",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/800px-Flag_of_Singapore.svg.png",
    name: "Singapore",
    fullName: "Republic of Singapore",
    nameInNativeLang: "新加坡共和国",
    capitalCity: "Singapore",
    largestCity: "Singapore",
    officialLanguages: "English, Malay, Mandarin, Tamil",
    religion: "Buddhism, Christianity, Islam, Taoism, Hinduism",
    population: "5,700,000",
    rankByPopulation: "114",
    independence: "09-Aug-1965",
    area: "728",
    currency: "Singapore Dollar (SGD)",
  },
  {
    code: "Sierra-Leone",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/800px-Flag_of_Sierra_Leone.svg.png",
    name: "Sierra Leone",
    fullName: "Republic of Sierra Leone",
    nameInNativeLang: "Republic of Sierra Leone",
    capitalCity: "Freetown",
    largestCity: "Freetown",
    officialLanguages: "English",
    religion: "Islam, Christianity",
    population: "8,600,000",
    rankByPopulation: "127",
    independence: "27-Apr-1961",
    area: "71,740",
    currency: "Sierra Leonean Leone (SLL)",
  },

  {
    code: "Somalia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/800px-Flag_of_Somalia.svg.png",
    name: "Somalia",
    fullName: "Federal Republic of Somalia",
    nameInNativeLang: "Jamhuuriyadda Soomaaliya",
    capitalCity: "Mogadishu",
    largestCity: "Mogadishu",
    officialLanguages: "Somali, Arabic",
    religion: "Islam",
    population: "18,100,000",
    rankByPopulation: "66",
    independence: "01-Jul-1960",
    area: "637,657",
    currency: "Somali Shilling (SOS)",
  },
  {
    code: "Serbia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png",
    name: "Serbia",
    fullName: "Republic of Serbia",
    nameInNativeLang: "Република Србија",
    capitalCity: "Belgrade",
    largestCity: "Belgrade",
    officialLanguages: "Serbian",
    religion: "Christianity",
    population: "6,700,000",
    rankByPopulation: "120",
    independence: "05-Jun-2006",
    area: "77,474",
    currency: "Serbian Dinar (RSD)",
  },
  {
    code: "Sweden",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/800px-Flag_of_Sweden.svg.png",
    name: "Sweden",
    fullName: "Kingdom of Sweden",
    nameInNativeLang: "Sverige",
    capitalCity: "Stockholm",
    largestCity: "Stockholm",
    officialLanguages: "Swedish",
    religion: "Christianity",
    population: "10,500,000",
    rankByPopulation: "90",
    independence: "06-Jun-1809",
    area: "450,295",
    currency: "Swedish Krona (SEK)",
  },

  {
    code: "Syria",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/800px-Flag_of_Syria.svg.png",
    name: "Syria",
    fullName: "Syrian Arab Republic",
    nameInNativeLang: "الجمهورية العربية السورية",
    capitalCity: "Damascus",
    largestCity: "Aleppo",
    officialLanguages: "Arabic",
    religion: "Islam",
    population: "24,600,000",
    rankByPopulation: "55",
    independence: "17-Apr-1946",
    area: "185,180",
    currency: "Syrian Pound (SYP)",
  },

  {
    code: "Togo",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/1024px-Flag_of_Togo.svg.png",
    name: "Togo",
    fullName: "Togolese Republic",
    nameInNativeLang: "République Togolaise",
    capitalCity: "Lomé",
    largestCity: "Lomé",
    officialLanguages: "French",
    religion: "Christianity, Islam, Traditional",
    population: "8,500,000",
    rankByPopulation: "135",
    independence: "27-Apr-1960",
    area: "56,785",
    currency: "West African CFA franc (XOF)",
  },
  {
    code: "Thailand",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/800px-Flag_of_Thailand.svg.png",
    name: "Thailand",
    fullName: "Kingdom of Thailand",
    nameInNativeLang: "ประเทศไทย",
    capitalCity: "Bangkok",
    largestCity: "Bangkok",
    officialLanguages: "Thai",
    religion: "Buddhism",
    population: "70,300,000",
    rankByPopulation: "20",
    independence: "13-Oct-1238",
    area: "513,120",
    currency: "Thai Baht (THB)",
  },
  {
    code: "Timor-Leste",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/1280px-Flag_of_East_Timor.svg.png",
    name: "Timor-Leste",
    fullName: "Democratic Republic of Timor-Leste",
    nameInNativeLang: "Repúblika Demokratika Timor-Leste",
    capitalCity: "Dili",
    largestCity: "Dili",
    officialLanguages: "Tetum, Portuguese",
    religion: "Christianity",
    population: "1,400,000",
    rankByPopulation: "166",
    independence: "20-May-2002",
    area: "14,874",
    currency: "United States Dollar (USD)",
  },
  {
    code: "Trinidad",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/1024px-Flag_of_Trinidad_and_Tobago.svg.png",
    name: "Trinidad & Tobago",
    fullName: "Republic of Trinidad and Tobago",
    nameInNativeLang: "Republic of Trinidad and Tobago",
    capitalCity: "Port of Spain",
    largestCity: "Port of Spain",
    officialLanguages: "English",
    religion: "Christianity",
    population: "1,500,000",
    rankByPopulation: "162",
    independence: "31-Aug-1962",
    area: "5,128",
    currency: "Trinidad and Tobago Dollar (TTD)",
  },
  {
    code: "Turkey",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/800px-Flag_of_Turkey.svg.png",
    name: "Turkey",
    fullName: "Republic of Turkey",
    nameInNativeLang: "Türkiye Cumhuriyeti",
    capitalCity: "Ankara",
    largestCity: "Istanbul",
    officialLanguages: "Turkish",
    religion: "Islam",
    population: "86,600,000",
    rankByPopulation: "18",
    independence: "23-Apr-1920",
    area: "783,356",
    currency: "Turkish Lira (TRY)",
  },
  {
    code: "Uganda",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/800px-Flag_of_Uganda.svg.png",
    name: "Uganda",
    fullName: "Republic of Uganda",
    nameInNativeLang: "República de Uganda",
    capitalCity: "Kampala",
    largestCity: "Kampala",
    officialLanguages: "English, Swahili",
    religion: "Christianity",
    population: "48,000,000",
    rankByPopulation: "34",
    independence: "09-Oct-1962",
    area: "241,038",
    currency: "Ugandan Shilling (UGX)",
  },
  {
    code: "Ukraine",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/800px-Flag_of_Ukraine.svg.png",
    name: "Ukraine",
    fullName: "Ukraine",
    nameInNativeLang: "Україна",
    capitalCity: "Kyiv",
    largestCity: "Kyiv",
    officialLanguages: "Ukrainian",
    religion: "Christianity",
    population: "43,800,000",
    rankByPopulation: "37",
    independence: "24-Aug-1991",
    area: "603,500",
    currency: "Ukrainian Hryvnia (UAH)",
  },
  {
    code: "Uruguay",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/800px-Flag_of_Uruguay.svg.png",
    name: "Uruguay",
    fullName: "Eastern Republic of Uruguay",
    nameInNativeLang: "República Oriental del Uruguay",
    capitalCity: "Montevideo",
    largestCity: "Montevideo",
    officialLanguages: "Spanish, Portuguese",
    religion: "Christianity",
    population: "3,500,000",
    rankByPopulation: "143",
    independence: "25-Aug-1825",
    area: "176,215",
    currency: "Uruguayan Peso (UYU)",
  },
  {
    code: "USA",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg/800px-Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg.png",
    name: "United States",
    fullName: "United States of America",
    nameInNativeLang: "United States",
    capitalCity: "Washington, D.C.",
    largestCity: "New York City",
    officialLanguages: "None (de facto: English)",
    religion: "Christianity",
    population: "332,900,000",
    rankByPopulation: "3",
    independence: "04-Jul-1776",
    area: "9,525,067",
    currency: "United States Dollar (USD)",
  },
  {
    code: "Venezuela",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/800px-Flag_of_Venezuela.svg.png",
    name: "Venezuela",
    fullName: "Bolivarian Republic of Venezuela",
    nameInNativeLang: "República Bolivariana de Venezuela",
    capitalCity: "Caracas",
    largestCity: "Caracas",
    officialLanguages: "Spanish",
    religion: "Christianity",
    population: "32,200,000",
    rankByPopulation: "50",
    independence: "05-Jul-1811",
    area: "916,445",
    currency: "Venezuelan Bolívar (VES)",
  },
  {
    code: "Vietnam",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/800px-Flag_of_Vietnam.svg.png",
    name: "Vietnam",
    fullName: "Socialist Republic of Vietnam",
    nameInNativeLang: "Cộng hòa Xã hội chủ nghĩa Việt Nam",
    capitalCity: "Hanoi",
    largestCity: "Ho Chi Minh City",
    officialLanguages: "Vietnamese",
    religion: "Buddhism, Christianity",
    population: "98,300,000",
    rankByPopulation: "15",
    independence: "02-Sep-1945",
    area: "331,210",
    currency: "Vietnamese Dong (VND)",
  },
  {
    code: "South-Africa",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/800px-Flag_of_South_Africa.svg.png",
    name: "South Africa",
    fullName: "Republic of South Africa",
    nameInNativeLang: "Republic of South Africa",
    capitalCity: "Pretoria, Bloemfontein, Cape Town",
    largestCity: "Johannesburg",
    officialLanguages:
      "11 languages, including Afrikaans, English, isiZulu, isiXhosa",
    religion: "Christianity",
    population: "60,000,000",
    rankByPopulation: "25",
    independence: "27-Apr-1994",
    area: "1,221,037",
    currency: "South African Rand (ZAR)",
  },
  {
    code: "Zambia",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/800px-Flag_of_Zambia.svg.png",
    name: "Zambia",
    fullName: "Republic of Zambia",
    nameInNativeLang: "Republic of Zambia",
    capitalCity: "Lusaka",
    largestCity: "Lusaka",
    officialLanguages: "English",
    religion: "Christianity",
    population: "19,600,000",
    rankByPopulation: "60",
    independence: "24-Oct-1964",
    area: "752,612",
    currency: "Zambian Kwacha (ZMW)",
  },
  {
    code: "Zimbabwe",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/800px-Flag_of_Zimbabwe.svg.png",
    name: "Zimbabwe",
    fullName: "Republic of Zimbabwe",
    nameInNativeLang: "Republic of Zimbabwe",
    capitalCity: "Harare",
    largestCity: "Harare",
    officialLanguages: "English, Shona, Sindebele",
    religion: "Christianity",
    population: "16,700,000",
    rankByPopulation: "70",
    independence: "18-Apr-1980",
    area: "390,757",
    currency: "Zimbabwean Dollar (ZWL)",
  },
];

export default CountryData;
