import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../../components/header";
import Footer from "../../components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD:Day06-of-30DaysNextjs/src/app/layout.tsx
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
>>>>>>> fb5b0ba1be3053be82d64156ab3d3a917c740e7c:src/app/layout.tsx
        {children}
        <Footer />
      </body>
    </html>
  );
}
